"""V2: what an exported plot or table says about itself once it leaves the app.

A PNG in a folder and a CSV in a spreadsheet have lost every label the app drew
around them. These tests open the real simulators, export through the real code
path, and read the files back.
"""

from __future__ import annotations

import pytest

from cosmos import __version__, provenance


@pytest.fixture(scope="module")
def sims(qt_app):
    """One live instance of each simulator these tests drive."""
    from cosmos.gui.simulators.registry import SIMULATORS

    return {i: SIMULATORS[i].create() for i in ("S5", "S6", "S16", "S19", "S23", "S24")}


def plot_of(sim, name: str):
    from cosmos.gui.widgets.plot import PlotWidget

    found = [p for p in sim.findChildren(PlotWidget) if p._name == name]
    assert found, f"no plot called {name}"
    return found[0]


# --------------------------------------------------------------- the note itself

def test_the_note_names_the_app_and_the_version():
    note = provenance.export_note("hubble diagram", simulator_id="S5", simulator_title="Hubble Diagram Fitter")
    assert note[0] == f"Cosmos {__version__} — hubble diagram"
    assert note[1] == "Simulator S5 · Hubble Diagram Fitter"
    assert note[-1].startswith("Exported ")
    assert provenance.HOME in note[-1]


def test_a_simulator_that_can_show_either_kind_says_so():
    """S5 offers Hubble's real galaxies and a synthetic sample; a guess would be a lie."""
    line = provenance.describe_sources("S5")
    assert "both real measurements" in line
    assert "Hubble's 1929 galaxies" in line


def test_a_simulator_with_only_real_data_cites_it():
    line = provenance.describe_sources("S24")
    assert line.startswith("Real measurements:")
    assert "Bennett" in line


def test_a_simulator_with_only_generated_data_admits_it():
    line = provenance.describe_sources("S13")
    assert line.startswith("Generated by Cosmos, not measured:")


def test_a_simulator_that_plots_pure_theory_says_that_too():
    assert provenance.describe_sources("S1") == "Computed by Cosmos from the model, not measured."


def test_the_simulator_own_words_win_over_the_standing_description():
    note = provenance.export_note("x", simulator_id="S5", detail=["Something only S5 knows."])
    assert "Something only S5 knows." in note
    assert not any("both real measurements" in line for line in note)


# ------------------------------------------------- what each simulator declares

def test_the_hubble_fitter_distinguishes_its_two_samples(sims):
    sim = sims["S5"]
    sim.selector.setCurrentIndex(sim.selector.findData("hubble1929"))
    assert "Real measurements" in sim.provenance()[0]
    sim.selector.setCurrentIndex(sim.selector.findData("simulated_modern"))
    assert sim.provenance()[0].startswith("Generated by Cosmos, not measured")


def test_the_rotation_curve_names_the_galaxy_it_measured(sims):
    sim = sims["S6"]
    assert sim.provenance()[0].startswith("Generated by Cosmos, not measured")
    for i in range(sim.galaxy_box.count()):
        if "NGC" in sim.galaxy_box.itemText(i):
            sim.galaxy_box.setCurrentIndex(i)
            break
    line = sim.provenance()[0]
    assert line.startswith("Real measurements: NGC")
    assert "Lelli" in line


def test_the_supernova_simulator_marks_the_pantheon_sample(sims):
    sim = sims["S16"]
    for i in range(sim.sample_box.count()):
        sim.sample_box.setCurrentIndex(i)
        line = sim.provenance()[0]
        expected = "Real measurements" if sim.sample.real else "Generated by Cosmos, not measured"
        assert line.startswith(expected), sim.sample_box.itemText(i)


def test_the_mcmc_explorer_records_the_chain_that_made_the_contours(sims):
    lines = sims["S19"].provenance()
    assert any("Chain:" in line and "seed" in line for line in lines)


def test_the_slice_simulator_tells_the_mock_from_the_sky(sims):
    sim = sims["S23"]
    assert sim.provenance("sdss_slice")[0].startswith("Real measurements: SDSS DR18")
    assert sim.provenance("redshift_slice")[0].startswith("Generated by Cosmos, not measured")


def test_the_sky_viewer_says_what_was_done_to_the_map(sims):
    lines = sims["S24"].provenance()
    assert lines[0].startswith("Real measurements: the WMAP nine-year ILC map")
    assert any("resampled from HEALPix" in line for line in lines)
    assert any(line.startswith("As shown here:") for line in lines)


# ------------------------------------------------------------ the files produced

def test_an_exported_csv_carries_the_note_above_the_numbers(tmp_path, sims):
    from cosmos.gui.widgets.plot import write_csv

    sim = sims["S5"]
    sim.selector.setCurrentIndex(sim.selector.findData("hubble1929"))
    plot = plot_of(sim, "hubble_diagram")
    headers, rows = plot._csv()
    path = tmp_path / "out.csv"
    write_csv(str(path), headers, rows, note=plot.provenance())

    lines = path.read_text(encoding="utf-8").splitlines()
    comments = [line for line in lines if line.startswith("#")]
    assert comments, "no provenance above the table"
    assert f"Cosmos {__version__}" in comments[0]
    assert any("Real measurements" in line for line in comments)
    assert any("Simulator S5" in line for line in comments)
    # The table itself is untouched: the first non-comment line is still the header.
    body = [line for line in lines if not line.startswith("#")]
    assert body[0].split(",")[0] == headers[0]
    assert len(body) == len(rows) + 1


def test_a_csv_with_no_note_is_exactly_what_it_always_was(tmp_path):
    from cosmos.gui.widgets.plot import write_csv

    path = tmp_path / "plain.csv"
    write_csv(str(path), ["a", "b"], [[1, 2], [3, 4]])
    assert path.read_text(encoding="utf-8").splitlines() == ["a,b", "1,2", "3,4"]


@pytest.fixture
def saving_to(monkeypatch, tmp_path):
    """Answer the save dialog with a path, so the real export path can run."""
    def choose(name: str):
        path = tmp_path / name
        monkeypatch.setattr("cosmos.gui.widgets.plot.QFileDialog.getSaveFileName",
                            staticmethod(lambda *a, **k: (str(path), "")))
        return path
    return choose


def test_an_exported_image_carries_the_note_in_its_metadata(saving_to, sims):
    from PIL import Image

    plot = plot_of(sims["S24"], "cmb_sky")
    plot._draw(plot.figure)                      # offscreen, the canvas is never laid out
    path = saving_to("sky.png")
    plot.export_image()

    assert path.is_file()
    with Image.open(path) as image:
        text = image.text
    assert f"Cosmos {__version__}" in text["Software"]
    assert "WMAP nine-year ILC map" in text["Description"]
    assert "Simulator S24" in text["Description"]


def test_an_exported_svg_gets_only_the_keys_svg_knows(saving_to, sims):
    plot = plot_of(sims["S5"], "hubble_diagram")
    plot._draw(plot.figure)
    path = saving_to("hubble.svg")
    plot.export_image()

    body = path.read_text(encoding="utf-8")
    assert "Hubble" in body
    assert "<dc:description>" in body


def test_exporting_leaves_the_figure_as_it_found_it(saving_to, sims):
    plot = plot_of(sims["S5"], "hubble_diagram")
    plot._draw(plot.figure)
    before = len(plot.figure.texts)
    saving_to("again.png")
    plot.export_image()
    assert len(plot.figure.texts) == before, "the caption was left on the live figure"


def test_the_plot_finds_the_simulator_it_lives_in(sims):
    plot = plot_of(sims["S16"], "supernova_hubble_diagram")
    assert plot.owning_simulator() is sims["S16"]
    note = plot.provenance()
    assert "Simulator S16" in note[1]


def test_a_plot_outside_a_simulator_still_says_where_it_came_from(qt_app):
    from cosmos.gui.widgets.plot import PlotWidget

    plot = PlotWidget(lambda fig: fig.add_subplot().plot([0, 1], [0, 1]), export_name="loose_plot")
    note = plot.provenance()
    assert note[0] == f"Cosmos {__version__} — loose plot"
    assert plot.owning_simulator() is None
